### ISSUE TITLE
How do you login?

### ISSUE THREAD

**Issue by JohnDeeBDD** [stanfordio/truthbrush#10]
**How do you login anyway? Could you give an example?**

I tried from the command line:

truthbrush user realDonaldTrump

Traceback (most recent call last):
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/bin/truthbrush", line 5, in <module>
    cli()
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/johndee/.cache/pypoetry/virtualenvs/truthbrush-A6vRjGNK-py3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/johndee/truthbrush/truthbrush/cli.py", line 39, in user
    print(json.dumps(api.lookup(handle)))
  File "/home/johndee/truthbrush/truthbrush/api.py", line 129, in lookup
    self.__check_login()
  File "/home/johndee/truthbrush/truthbrush/api.py", line 48, in __check_login
    raise LoginErrorException("Username is missing.")
truthbrush.api.LoginErrorException: Username is missing.

**Comment by lxcode** [comment]
Hi John — we just updated the README with usage info that should solve this for you.

**Comment by JohnDeeBDD** [comment]
Thanks for the help! FYI is someone else is reading, you need to add namespaced creds to the environment i.e.

export TRUTHSOCIAL_USERNAME=your_username
export TRUTHSOCIAL_PASSWORD=your_password
