### ISSUE TITLE
Getting the below error 

### ISSUE THREAD

**Issue by prachisadarangani** [stanfordio/truthbrush#14]
Hello, 

I had executed the command: !truthbrush statuses "realDonaldTrump" before and it was working just fine but now that I'm trying to use the same command, I'm getting the below error.

Traceback (most recent call last):
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='truthsocial.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup?acct=realDonaldTrump (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prachisadarangani/opt/anaconda3/bin/truthbrush", line 8, in <module>
    sys.exit(cli())
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/truthbrush/cli.py", line 125, in statuses
    for page in api.pull_statuses(username, created_after, replies):
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/truthbrush/api.py", line 255, in pull_statuses
    id = self.lookup(username)["id"]
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/truthbrush/api.py", line 131, in lookup
    return self._get("/v1/accounts/lookup", params=dict(acct=user_handle))
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/truthbrush/api.py", line 89, in _get
    resp = self._make_session().get(
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/prachisadarangani/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='truthsocial.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup?acct=realDonaldTrump (Caused by ResponseError('too many 403 error responses'))

Do you know what this error is about and how can I resolve it?

**Comment by rahm-hopkins** [comment]
I had been getting this error, but pulled latest code yesterday and it worked.  This morning, I am getting 403 error again:

MaxRetryError                             Traceback (most recent call last)
File c:\Users\USER_1\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File c:\Users\USER_1\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:878, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    877     log.debug("Retry: %s", url)
--> 878     return self.urlopen(
    879         method,
    880         url,
    881         body,
...
--> 556     raise RetryError(e, request=request)
    558 if isinstance(e.reason, _ProxyError):
    559     raise ProxyError(e, request=request)

RetryError: HTTPSConnectionPool(host='truthsocial.com', port=443): Max retries exceeded with url: /api/v2/search?q=batman&resolve=4&limit=40&type=statuses&offset=0&min_id=0 (Caused by ResponseError('too many 403 error responses'))

**Comment by lxcode** [comment]
Can you give a try to the current revision?

**Comment by rahm-hopkins** [comment]
I pulled today and tried the following, got 403:

from truthbrush import Api
truth = Api(username=username,password=password)
truth.lookup(user_handle='JackPosobiec')

MaxRetryError                             Traceback (most recent call last)
File [c:\Users\USER_1\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py:489](file:///C:/Users/USER_1/AppData/Local/Programs/Python/Python39/lib/site-packages/requests/adapters.py:489), in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File [c:\Users\USER_1\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:878](file:///C:/Users/USER_1/AppData/Local/Programs/Python/Python39/lib/site-packages/urllib3/connectionpool.py:878), in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    877     log.debug("Retry: %s", url)
--> 878     return self.urlopen(
    879         method,
    880         url,
    881         body,
...
--> 556     raise RetryError(e, request=request)
    558 if isinstance(e.reason, _ProxyError):
    559     raise ProxyError(e, request=request)

RetryError: HTTPSConnectionPool(host='truthsocial.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup?acct=JackPosobiec (Caused by ResponseError('too many 403 error responses'))
