### ISSUE TITLE
Search errors - empty jsons

### ISSUE THREAD

**Issue by jason-lange** [stanfordio/truthbrush#27]
I'm getting errors on all the keyword searches I run. It appears that truthbrush is getting tripped up by empty jsons. 

background:
* I've cloned the most recent version: !pip install git+https://github.com/stanfordio/truthbrush.git  
* I'm able to pull all the statuses of a user without getting an error: !truthbrush statuses realDonaldTrump > trump_4_4_24.json

problem:
* When trying to search for keywords, I'm able get many, many responses with queries like this: !truthbrush search --searchtype statuses "trump"  > 04_04_24_trump.json
* But they all break during the search, and give the error copied below, which appears to be because truthbrush is encountering an empty json. 
* I get the same behavior for searches with other terms.

questions:
* Is this normal behavior, in that a keyword search always runs until it breaks?
* If not, is there a way to skip empty json responses?
Many thanks,
Jason

Error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Scripts\truthbrush.exe\__main__.py", line 7, in <module>
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\truthbrush\cli.py", line 55, in search
    for page in api.search(searchtype, query, limit, resolve):
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\truthbrush\api.py", line 162, in search
    resp = self._get(
           ^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\truthbrush\api.py", line 105, in _get
    return resp.json()
           ^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\site-packages\curl_cffi\requests\models.py", line 129, in json
    return loads(self.content, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\8013352\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lxcode** [comment]
This should be fixed in the current version, please reopen if it recurs.
