### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'

### ISSUE THREAD

**Issue by eelegiap** [stanfordio/truthbrush#37]
Any action with `truthbrush` in the CLI is resulting in the same error for me:
```Traceback (most recent call last):
  File "/.venv/bin/truthbrush", line 5, in <module>
    from truthbrush.cli import cli
  File "/.venv/lib/python3.9/site-packages/truthbrush/__init__.py", line 1, in <module>
    from truthbrush.api import Api
  File "/.venv/lib/python3.9/site-packages/truthbrush/api.py", line 42, in <module>
    class Api:
  File "/.venv/lib/python3.9/site-packages/truthbrush/api.py", line 148, in Api
    def userLikes(self, post: str, top_num: int = 40) -> bool | Any:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'```

**Comment by eelegiap** [comment]
Ah my bad here. I was on Python 3.9.6, but the `|` operator is only understood in Python 3.10+.

**Comment by lxcode** [comment]
Our bad since we had the minimum set to 3.9. Fixed now, thanks!
