### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by mmosleh** [stanfordio/truthbrush#40]
It seems the login method doesn't work properly. The username and password I exported as environment varialbe work on the website. But it doesn't work with the API. It used to be working fine. I pulled the most recent version from GitHub but doesn't seem working (see below). Could it be I need to use a particular IP/Proxy?

Thank you!

`truthbrush search --searchtype accounts trump`

```
2024-10-07 11:48:57.777 | ERROR    | truthbrush.api:get_auth_id:468 - Failed login request: HTTP Error 403: 
2024-10-07 11:48:57.777 | WARNING  | truthbrush.api:__check_login:67 - Using token None
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/truthbrush/api.py", line 106, in _get
    "Authorization": "Bearer " + self.auth_id,
                     ~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/truthbrush", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/truthbrush/cli.py", line 85, in search
    for page in api.search(searchtype, query, limit, resolve):
  File "/opt/anaconda3/lib/python3.12/site-packages/truthbrush/api.py", line 225, in search
    resp = self._get(
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/truthbrush/api.py", line 110, in _get
    except curl_cffi.curl.CurlError as e:
           ^^^^^^^^^
NameError: name 'curl_cffi' is not defined

```

**Comment by lxcode** [comment]
That command line seems to work fine for me in the current git, so I think your guess regarding IP is correct. Try the most recent commit; otherwise, an alternative might be to grab the auth token from your browser and use that instead of username+pass.

**Comment by mmosleh** [comment]
Thank you. Will try it.
